title = 'unimi-calendar'
baseURL = 'https://raffaelecalza.github.io/unimi-calendar/'
theme = "unimi-calendar"
defaultContentLanguage = "it"
disableKinds = ["sitemap", "RSS", "section"]

[params]
description = "Sincronizza l'orario delle lezioni con il tuo calendario, senza utilizzare l'app di unimi"
unimiUrl = "https://easystaff.divsi.unimi.it/PortaleStudenti/index.php?view=easycourse"
githubUrl = "https://github.com/raffaelecalza/unimi-calendar/"
footer = "Built with â¤ï¸ and some â˜•ï¸"

[languages]
  [languages.en]
    description = "Synchronise your class schedule with your calendar, without using the unimi app"
    weight = 2
    flag = "ğŸ‡¬ğŸ‡§"
    stringsJS = "js/strings_en.js"
  [languages.it]
    weight = 1
    flag = "ğŸ‡®ğŸ‡¹"
    stringsJS = "js/strings_it.js"